apiVersion: apps/v1
kind: Deployment
metadata:
  name: pharos-ai-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pharos-ai
  template:
    metadata:
      labels:
        app: pharos-ai
    spec:
      containers:
      - name: pharos-ai
        image: pharos-ai-api:latest
        ports:
        - containerPort: 5000

      